"""Build the checked-in OFL font subsets; normal builds do not need Python/network.

Input: .local/font-sources/{song,kai,round}.ttf and corresponding *-OFL.txt.
Keep GB2312 plus Latin/punctuation and all source UI characters. Rename modified
families and preserve upstream copyright/license records and full OFL notices.
"""
from pathlib import Path
import json
import shutil
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'wearable/src/common/fonts'
OUT.mkdir(parents=True, exist_ok=True)
chars = set(range(0x20, 0x7f)) | set(range(0x2000, 0x2070)) | set(range(0x3000, 0x3040)) | set(range(0xff00, 0xffef))
for high in range(0xa1, 0xf8):
    for low in range(0xa1, 0xff):
        try:
            chars.update(map(ord, bytes([high, low]).decode('gb2312')))
        except UnicodeDecodeError:
            pass
for file in (ROOT / 'wearable/src').rglob('*'):
    if file.suffix in ('.js', '.ux') and file.name != 'font-coverage.js':
        chars.update(map(ord, file.read_text(encoding='utf-8')))

coverage = {}
for key in ('song', 'kai', 'round'):
    family = 'Band' + key.title()
    font = TTFont(ROOT / '.local/font-sources' / (key + '.ttf'), recalcTimestamp=False)
    options = subset.Options()
    options.name_IDs = ['*']
    options.name_languages = ['*']
    options.name_legacy = True
    options.recalc_timestamp = False
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=chars)
    sub.subset(font)
    # Subsets are derivative fonts: use unique names, retain the license records.
    for record in font['name'].names:
        if record.nameID in (1, 3, 4, 6, 16, 17):
            value = 'Regular' if record.nameID == 17 else family
            record.string = value.encode(record.getEncoding())
    font.save(OUT / (family + '.ttf'))
    shutil.copyfile(ROOT / '.local/font-sources' / (key + '-OFL.txt'), OUT / (family + '-OFL.txt'))
    points = sorted(font.getBestCmap())
    # Compact BMP bitset: avoid thousands of nested JS arrays on the band.
    bits = [0] * (65536 // 4)
    for point in points:
        if point < 65536:
            bits[point >> 2] |= 1 << (point & 3)
    coverage[key] = ''.join(format(value, 'x') for value in bits).rstrip('0')
    print(f'{family}: {len(points)} codepoints, {(OUT / (family + ".ttf")).stat().st_size} bytes')
(OUT.parent / 'font-coverage.js').write_text(
    '// Generated by tools/prepare-band-fonts.py. Used to retain system rendering for missing glyphs.\n'
    + 'module.exports = ' + json.dumps(coverage, separators=(',', ':')) + ';\n', encoding='utf-8')
